### ISSUE TITLE
Updating Digital Twins from the IoT Hub 

### ISSUE THREAD

**Issue by nesvieraquetocos** [Azure-Samples/IoTDemos#41]
Use the following command to create the system-managed identity. Take note of the principalId field in the output.

this appears 

The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'identity'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 664, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 727, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 720, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rg200gj8\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 698, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 331, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py", line 816, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-7as_bwui\azure\cli\command_modules\appservice\custom.py", line 800, in assign_identity
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\arm.py", line 1061, in assign_identity
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-7as_bwui\azure\cli\command_modules\appservice\custom.py", line 773, in setter
AttributeError: 'NoneType' object has no attribute 'identity'

how can I solve that ? Thank you

**Comment by Teodelas** [comment]
Hi, please make sure you're running the latest version of the AZ CLI. 
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

Alternatively, run the commands from the Azure cloud shell.
https://docs.microsoft.com/en-us/azure/cloud-shell/overview

**Comment by nesvieraquetocos** [comment]
thank you very much Teo
